//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Mainsite.xsd {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("DataSet1")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DataSet1 : global::System.Data.DataSet {
        
        private CC_PAC_075DataTable tableCC_PAC_075;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public DataSet1() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected DataSet1(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["CC_PAC_075"] != null)) {
                    base.Tables.Add(new CC_PAC_075DataTable(ds.Tables["CC_PAC_075"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public CC_PAC_075DataTable CC_PAC_075 {
            get {
                return this.tableCC_PAC_075;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            DataSet1 cln = ((DataSet1)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["CC_PAC_075"] != null)) {
                    base.Tables.Add(new CC_PAC_075DataTable(ds.Tables["CC_PAC_075"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableCC_PAC_075 = ((CC_PAC_075DataTable)(base.Tables["CC_PAC_075"]));
            if ((initTable == true)) {
                if ((this.tableCC_PAC_075 != null)) {
                    this.tableCC_PAC_075.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "DataSet1";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DataSet1.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableCC_PAC_075 = new CC_PAC_075DataTable();
            base.Tables.Add(this.tableCC_PAC_075);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeCC_PAC_075() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            DataSet1 ds = new DataSet1();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void CC_PAC_075RowChangeEventHandler(object sender, CC_PAC_075RowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class CC_PAC_075DataTable : global::System.Data.TypedTableBase<CC_PAC_075Row> {
            
            private global::System.Data.DataColumn columnPLANTA;
            
            private global::System.Data.DataColumn columnTURNO;
            
            private global::System.Data.DataColumn columnLINEA;
            
            private global::System.Data.DataColumn columnPROCESO;
            
            private global::System.Data.DataColumn columnLOTE;
            
            private global::System.Data.DataColumn columnPRODUCTOR;
            
            private global::System.Data.DataColumn columnVARIEDAD;
            
            private global::System.Data.DataColumn _column__Exportable_Estimado;
            
            private global::System.Data.DataColumn _column__Exportable_Descartador;
            
            private global::System.Data.DataColumn _column__Descarte_CAT_2;
            
            private global::System.Data.DataColumn _column__Descarte_CAT_3;
            
            private global::System.Data.DataColumn _columnCAT_1___Desecho_;
            
            private global::System.Data.DataColumn _columnCAT_2___Exportable_;
            
            private global::System.Data.DataColumn _columnCAT_3___Exportable_;
            
            private global::System.Data.DataColumn _column__Exportable_Descarte_Mesa_de_Selección;
            
            private global::System.Data.DataColumn _column__Exportable_Descarte_Manual_Linea;
            
            private global::System.Data.DataColumn columnCajasMedidas;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public CC_PAC_075DataTable() {
                this.TableName = "CC_PAC_075";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal CC_PAC_075DataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected CC_PAC_075DataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PLANTAColumn {
                get {
                    return this.columnPLANTA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn TURNOColumn {
                get {
                    return this.columnTURNO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn LINEAColumn {
                get {
                    return this.columnLINEA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PROCESOColumn {
                get {
                    return this.columnPROCESO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn LOTEColumn {
                get {
                    return this.columnLOTE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn PRODUCTORColumn {
                get {
                    return this.columnPRODUCTOR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn VARIEDADColumn {
                get {
                    return this.columnVARIEDAD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ___Exportable_EstimadoColumn {
                get {
                    return this._column__Exportable_Estimado;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ___Exportable_DescartadorColumn {
                get {
                    return this._column__Exportable_Descartador;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ___Descarte_CAT_2Column {
                get {
                    return this._column__Descarte_CAT_2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ___Descarte_CAT_3Column {
                get {
                    return this._column__Descarte_CAT_3;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn _CAT_1___Desecho_Column {
                get {
                    return this._columnCAT_1___Desecho_;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn _CAT_2___Exportable_Column {
                get {
                    return this._columnCAT_2___Exportable_;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn _CAT_3___Exportable_Column {
                get {
                    return this._columnCAT_3___Exportable_;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ___Exportable_Descarte_Mesa_de_SelecciónColumn {
                get {
                    return this._column__Exportable_Descarte_Mesa_de_Selección;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ___Exportable_Descarte_Manual_LineaColumn {
                get {
                    return this._column__Exportable_Descarte_Manual_Linea;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CajasMedidasColumn {
                get {
                    return this.columnCajasMedidas;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public CC_PAC_075Row this[int index] {
                get {
                    return ((CC_PAC_075Row)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event CC_PAC_075RowChangeEventHandler CC_PAC_075RowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event CC_PAC_075RowChangeEventHandler CC_PAC_075RowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event CC_PAC_075RowChangeEventHandler CC_PAC_075RowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event CC_PAC_075RowChangeEventHandler CC_PAC_075RowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddCC_PAC_075Row(CC_PAC_075Row row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public CC_PAC_075Row AddCC_PAC_075Row(
                        string PLANTA, 
                        string TURNO, 
                        string LINEA, 
                        string PROCESO, 
                        string LOTE, 
                        string PRODUCTOR, 
                        string VARIEDAD, 
                        decimal ___Exportable_Estimado, 
                        decimal ___Exportable_Descartador, 
                        decimal ___Descarte_CAT_2, 
                        decimal ___Descarte_CAT_3, 
                        decimal _CAT_1___Desecho_, 
                        decimal _CAT_2___Exportable_, 
                        decimal _CAT_3___Exportable_, 
                        decimal ___Exportable_Descarte_Mesa_de_Selección, 
                        decimal ___Exportable_Descarte_Manual_Linea, 
                        int CajasMedidas) {
                CC_PAC_075Row rowCC_PAC_075Row = ((CC_PAC_075Row)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        PLANTA,
                        TURNO,
                        LINEA,
                        PROCESO,
                        LOTE,
                        PRODUCTOR,
                        VARIEDAD,
                        ___Exportable_Estimado,
                        ___Exportable_Descartador,
                        ___Descarte_CAT_2,
                        ___Descarte_CAT_3,
                        _CAT_1___Desecho_,
                        _CAT_2___Exportable_,
                        _CAT_3___Exportable_,
                        ___Exportable_Descarte_Mesa_de_Selección,
                        ___Exportable_Descarte_Manual_Linea,
                        CajasMedidas};
                rowCC_PAC_075Row.ItemArray = columnValuesArray;
                this.Rows.Add(rowCC_PAC_075Row);
                return rowCC_PAC_075Row;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                CC_PAC_075DataTable cln = ((CC_PAC_075DataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new CC_PAC_075DataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnPLANTA = base.Columns["PLANTA"];
                this.columnTURNO = base.Columns["TURNO"];
                this.columnLINEA = base.Columns["LINEA"];
                this.columnPROCESO = base.Columns["PROCESO"];
                this.columnLOTE = base.Columns["LOTE"];
                this.columnPRODUCTOR = base.Columns["PRODUCTOR"];
                this.columnVARIEDAD = base.Columns["VARIEDAD"];
                this._column__Exportable_Estimado = base.Columns["% Exportable Estimado"];
                this._column__Exportable_Descartador = base.Columns["% Exportable Descartador"];
                this._column__Descarte_CAT_2 = base.Columns["% Descarte CAT 2"];
                this._column__Descarte_CAT_3 = base.Columns["% Descarte CAT 3"];
                this._columnCAT_1___Desecho_ = base.Columns["CAT 1 %(Desecho)"];
                this._columnCAT_2___Exportable_ = base.Columns["CAT 2 %(Exportable)"];
                this._columnCAT_3___Exportable_ = base.Columns["CAT 3 %(Exportable)"];
                this._column__Exportable_Descarte_Mesa_de_Selección = base.Columns["% Exportable Descarte Mesa de Selección"];
                this._column__Exportable_Descarte_Manual_Linea = base.Columns["% Exportable Descarte Manual Linea"];
                this.columnCajasMedidas = base.Columns["CajasMedidas"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnPLANTA = new global::System.Data.DataColumn("PLANTA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPLANTA);
                this.columnTURNO = new global::System.Data.DataColumn("TURNO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTURNO);
                this.columnLINEA = new global::System.Data.DataColumn("LINEA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLINEA);
                this.columnPROCESO = new global::System.Data.DataColumn("PROCESO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPROCESO);
                this.columnLOTE = new global::System.Data.DataColumn("LOTE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLOTE);
                this.columnPRODUCTOR = new global::System.Data.DataColumn("PRODUCTOR", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPRODUCTOR);
                this.columnVARIEDAD = new global::System.Data.DataColumn("VARIEDAD", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnVARIEDAD);
                this._column__Exportable_Estimado = new global::System.Data.DataColumn("% Exportable Estimado", typeof(decimal), null, global::System.Data.MappingType.Element);
                this._column__Exportable_Estimado.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_column__Exportable_Estimado");
                this._column__Exportable_Estimado.ExtendedProperties.Add("Generator_UserColumnName", "% Exportable Estimado");
                base.Columns.Add(this._column__Exportable_Estimado);
                this._column__Exportable_Descartador = new global::System.Data.DataColumn("% Exportable Descartador", typeof(decimal), null, global::System.Data.MappingType.Element);
                this._column__Exportable_Descartador.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_column__Exportable_Descartador");
                this._column__Exportable_Descartador.ExtendedProperties.Add("Generator_UserColumnName", "% Exportable Descartador");
                base.Columns.Add(this._column__Exportable_Descartador);
                this._column__Descarte_CAT_2 = new global::System.Data.DataColumn("% Descarte CAT 2", typeof(decimal), null, global::System.Data.MappingType.Element);
                this._column__Descarte_CAT_2.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_column__Descarte_CAT_2");
                this._column__Descarte_CAT_2.ExtendedProperties.Add("Generator_UserColumnName", "% Descarte CAT 2");
                base.Columns.Add(this._column__Descarte_CAT_2);
                this._column__Descarte_CAT_3 = new global::System.Data.DataColumn("% Descarte CAT 3", typeof(decimal), null, global::System.Data.MappingType.Element);
                this._column__Descarte_CAT_3.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_column__Descarte_CAT_3");
                this._column__Descarte_CAT_3.ExtendedProperties.Add("Generator_UserColumnName", "% Descarte CAT 3");
                base.Columns.Add(this._column__Descarte_CAT_3);
                this._columnCAT_1___Desecho_ = new global::System.Data.DataColumn("CAT 1 %(Desecho)", typeof(decimal), null, global::System.Data.MappingType.Element);
                this._columnCAT_1___Desecho_.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnCAT_1___Desecho_");
                this._columnCAT_1___Desecho_.ExtendedProperties.Add("Generator_UserColumnName", "CAT 1 %(Desecho)");
                base.Columns.Add(this._columnCAT_1___Desecho_);
                this._columnCAT_2___Exportable_ = new global::System.Data.DataColumn("CAT 2 %(Exportable)", typeof(decimal), null, global::System.Data.MappingType.Element);
                this._columnCAT_2___Exportable_.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnCAT_2___Exportable_");
                this._columnCAT_2___Exportable_.ExtendedProperties.Add("Generator_UserColumnName", "CAT 2 %(Exportable)");
                base.Columns.Add(this._columnCAT_2___Exportable_);
                this._columnCAT_3___Exportable_ = new global::System.Data.DataColumn("CAT 3 %(Exportable)", typeof(decimal), null, global::System.Data.MappingType.Element);
                this._columnCAT_3___Exportable_.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_columnCAT_3___Exportable_");
                this._columnCAT_3___Exportable_.ExtendedProperties.Add("Generator_UserColumnName", "CAT 3 %(Exportable)");
                base.Columns.Add(this._columnCAT_3___Exportable_);
                this._column__Exportable_Descarte_Mesa_de_Selección = new global::System.Data.DataColumn("% Exportable Descarte Mesa de Selección", typeof(decimal), null, global::System.Data.MappingType.Element);
                this._column__Exportable_Descarte_Mesa_de_Selección.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_column__Exportable_Descarte_Mesa_de_Selección");
                this._column__Exportable_Descarte_Mesa_de_Selección.ExtendedProperties.Add("Generator_UserColumnName", "% Exportable Descarte Mesa de Selección");
                base.Columns.Add(this._column__Exportable_Descarte_Mesa_de_Selección);
                this._column__Exportable_Descarte_Manual_Linea = new global::System.Data.DataColumn("% Exportable Descarte Manual Linea", typeof(decimal), null, global::System.Data.MappingType.Element);
                this._column__Exportable_Descarte_Manual_Linea.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "_column__Exportable_Descarte_Manual_Linea");
                this._column__Exportable_Descarte_Manual_Linea.ExtendedProperties.Add("Generator_UserColumnName", "% Exportable Descarte Manual Linea");
                base.Columns.Add(this._column__Exportable_Descarte_Manual_Linea);
                this.columnCajasMedidas = new global::System.Data.DataColumn("CajasMedidas", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCajasMedidas);
                this._column__Descarte_CAT_2.Caption = "% Exportable Descartador";
                this._column__Descarte_CAT_3.Caption = "% Exportable Descartador";
                this._columnCAT_1___Desecho_.Caption = "% Exportable Descartador";
                this._columnCAT_2___Exportable_.Caption = "% Exportable Descartador";
                this._columnCAT_3___Exportable_.Caption = "% Exportable Descartador";
                this._column__Exportable_Descarte_Mesa_de_Selección.Caption = "% Exportable Descartador";
                this._column__Exportable_Descarte_Manual_Linea.Caption = "% Exportable Descartador";
                this.columnCajasMedidas.Caption = "% Exportable Descartador";
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public CC_PAC_075Row NewCC_PAC_075Row() {
                return ((CC_PAC_075Row)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new CC_PAC_075Row(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(CC_PAC_075Row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.CC_PAC_075RowChanged != null)) {
                    this.CC_PAC_075RowChanged(this, new CC_PAC_075RowChangeEvent(((CC_PAC_075Row)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.CC_PAC_075RowChanging != null)) {
                    this.CC_PAC_075RowChanging(this, new CC_PAC_075RowChangeEvent(((CC_PAC_075Row)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.CC_PAC_075RowDeleted != null)) {
                    this.CC_PAC_075RowDeleted(this, new CC_PAC_075RowChangeEvent(((CC_PAC_075Row)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.CC_PAC_075RowDeleting != null)) {
                    this.CC_PAC_075RowDeleting(this, new CC_PAC_075RowChangeEvent(((CC_PAC_075Row)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveCC_PAC_075Row(CC_PAC_075Row row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                DataSet1 ds = new DataSet1();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "CC_PAC_075DataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class CC_PAC_075Row : global::System.Data.DataRow {
            
            private CC_PAC_075DataTable tableCC_PAC_075;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal CC_PAC_075Row(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableCC_PAC_075 = ((CC_PAC_075DataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string PLANTA {
                get {
                    try {
                        return ((string)(this[this.tableCC_PAC_075.PLANTAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'PLANTA\' de la tabla \'CC_PAC_075\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableCC_PAC_075.PLANTAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string TURNO {
                get {
                    try {
                        return ((string)(this[this.tableCC_PAC_075.TURNOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'TURNO\' de la tabla \'CC_PAC_075\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableCC_PAC_075.TURNOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string LINEA {
                get {
                    try {
                        return ((string)(this[this.tableCC_PAC_075.LINEAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'LINEA\' de la tabla \'CC_PAC_075\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableCC_PAC_075.LINEAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string PROCESO {
                get {
                    try {
                        return ((string)(this[this.tableCC_PAC_075.PROCESOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'PROCESO\' de la tabla \'CC_PAC_075\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableCC_PAC_075.PROCESOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string LOTE {
                get {
                    try {
                        return ((string)(this[this.tableCC_PAC_075.LOTEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'LOTE\' de la tabla \'CC_PAC_075\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableCC_PAC_075.LOTEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string PRODUCTOR {
                get {
                    try {
                        return ((string)(this[this.tableCC_PAC_075.PRODUCTORColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'PRODUCTOR\' de la tabla \'CC_PAC_075\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableCC_PAC_075.PRODUCTORColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string VARIEDAD {
                get {
                    try {
                        return ((string)(this[this.tableCC_PAC_075.VARIEDADColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'VARIEDAD\' de la tabla \'CC_PAC_075\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableCC_PAC_075.VARIEDADColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal ___Exportable_Estimado {
                get {
                    try {
                        return ((decimal)(this[this.tableCC_PAC_075.___Exportable_EstimadoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'% Exportable Estimado\' de la tabla \'CC_PAC_075\' es DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableCC_PAC_075.___Exportable_EstimadoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal ___Exportable_Descartador {
                get {
                    try {
                        return ((decimal)(this[this.tableCC_PAC_075.___Exportable_DescartadorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'% Exportable Descartador\' de la tabla \'CC_PAC_075\' es DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableCC_PAC_075.___Exportable_DescartadorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal ___Descarte_CAT_2 {
                get {
                    try {
                        return ((decimal)(this[this.tableCC_PAC_075.___Descarte_CAT_2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'% Descarte CAT 2\' de la tabla \'CC_PAC_075\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableCC_PAC_075.___Descarte_CAT_2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal ___Descarte_CAT_3 {
                get {
                    try {
                        return ((decimal)(this[this.tableCC_PAC_075.___Descarte_CAT_3Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'% Descarte CAT 3\' de la tabla \'CC_PAC_075\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableCC_PAC_075.___Descarte_CAT_3Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal _CAT_1___Desecho_ {
                get {
                    try {
                        return ((decimal)(this[this.tableCC_PAC_075._CAT_1___Desecho_Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'CAT 1 %(Desecho)\' de la tabla \'CC_PAC_075\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableCC_PAC_075._CAT_1___Desecho_Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal _CAT_2___Exportable_ {
                get {
                    try {
                        return ((decimal)(this[this.tableCC_PAC_075._CAT_2___Exportable_Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'CAT 2 %(Exportable)\' de la tabla \'CC_PAC_075\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableCC_PAC_075._CAT_2___Exportable_Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal _CAT_3___Exportable_ {
                get {
                    try {
                        return ((decimal)(this[this.tableCC_PAC_075._CAT_3___Exportable_Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'CAT 3 %(Exportable)\' de la tabla \'CC_PAC_075\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableCC_PAC_075._CAT_3___Exportable_Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal ___Exportable_Descarte_Mesa_de_Selección {
                get {
                    try {
                        return ((decimal)(this[this.tableCC_PAC_075.___Exportable_Descarte_Mesa_de_SelecciónColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'% Exportable Descarte Mesa de Selección\' de la tabla \'CC_" +
                                "PAC_075\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableCC_PAC_075.___Exportable_Descarte_Mesa_de_SelecciónColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public decimal ___Exportable_Descarte_Manual_Linea {
                get {
                    try {
                        return ((decimal)(this[this.tableCC_PAC_075.___Exportable_Descarte_Manual_LineaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'% Exportable Descarte Manual Linea\' de la tabla \'CC_PAC_0" +
                                "75\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableCC_PAC_075.___Exportable_Descarte_Manual_LineaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int CajasMedidas {
                get {
                    try {
                        return ((int)(this[this.tableCC_PAC_075.CajasMedidasColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'CajasMedidas\' de la tabla \'CC_PAC_075\' es DBNull.", e);
                    }
                }
                set {
                    this[this.tableCC_PAC_075.CajasMedidasColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPLANTANull() {
                return this.IsNull(this.tableCC_PAC_075.PLANTAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPLANTANull() {
                this[this.tableCC_PAC_075.PLANTAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTURNONull() {
                return this.IsNull(this.tableCC_PAC_075.TURNOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTURNONull() {
                this[this.tableCC_PAC_075.TURNOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsLINEANull() {
                return this.IsNull(this.tableCC_PAC_075.LINEAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetLINEANull() {
                this[this.tableCC_PAC_075.LINEAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPROCESONull() {
                return this.IsNull(this.tableCC_PAC_075.PROCESOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPROCESONull() {
                this[this.tableCC_PAC_075.PROCESOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsLOTENull() {
                return this.IsNull(this.tableCC_PAC_075.LOTEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetLOTENull() {
                this[this.tableCC_PAC_075.LOTEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsPRODUCTORNull() {
                return this.IsNull(this.tableCC_PAC_075.PRODUCTORColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetPRODUCTORNull() {
                this[this.tableCC_PAC_075.PRODUCTORColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsVARIEDADNull() {
                return this.IsNull(this.tableCC_PAC_075.VARIEDADColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetVARIEDADNull() {
                this[this.tableCC_PAC_075.VARIEDADColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is___Exportable_EstimadoNull() {
                return this.IsNull(this.tableCC_PAC_075.___Exportable_EstimadoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set___Exportable_EstimadoNull() {
                this[this.tableCC_PAC_075.___Exportable_EstimadoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is___Exportable_DescartadorNull() {
                return this.IsNull(this.tableCC_PAC_075.___Exportable_DescartadorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set___Exportable_DescartadorNull() {
                this[this.tableCC_PAC_075.___Exportable_DescartadorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is___Descarte_CAT_2Null() {
                return this.IsNull(this.tableCC_PAC_075.___Descarte_CAT_2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set___Descarte_CAT_2Null() {
                this[this.tableCC_PAC_075.___Descarte_CAT_2Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is___Descarte_CAT_3Null() {
                return this.IsNull(this.tableCC_PAC_075.___Descarte_CAT_3Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set___Descarte_CAT_3Null() {
                this[this.tableCC_PAC_075.___Descarte_CAT_3Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_CAT_1___Desecho_Null() {
                return this.IsNull(this.tableCC_PAC_075._CAT_1___Desecho_Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_CAT_1___Desecho_Null() {
                this[this.tableCC_PAC_075._CAT_1___Desecho_Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_CAT_2___Exportable_Null() {
                return this.IsNull(this.tableCC_PAC_075._CAT_2___Exportable_Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_CAT_2___Exportable_Null() {
                this[this.tableCC_PAC_075._CAT_2___Exportable_Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is_CAT_3___Exportable_Null() {
                return this.IsNull(this.tableCC_PAC_075._CAT_3___Exportable_Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set_CAT_3___Exportable_Null() {
                this[this.tableCC_PAC_075._CAT_3___Exportable_Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is___Exportable_Descarte_Mesa_de_SelecciónNull() {
                return this.IsNull(this.tableCC_PAC_075.___Exportable_Descarte_Mesa_de_SelecciónColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set___Exportable_Descarte_Mesa_de_SelecciónNull() {
                this[this.tableCC_PAC_075.___Exportable_Descarte_Mesa_de_SelecciónColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Is___Exportable_Descarte_Manual_LineaNull() {
                return this.IsNull(this.tableCC_PAC_075.___Exportable_Descarte_Manual_LineaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Set___Exportable_Descarte_Manual_LineaNull() {
                this[this.tableCC_PAC_075.___Exportable_Descarte_Manual_LineaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsCajasMedidasNull() {
                return this.IsNull(this.tableCC_PAC_075.CajasMedidasColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetCajasMedidasNull() {
                this[this.tableCC_PAC_075.CajasMedidasColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class CC_PAC_075RowChangeEvent : global::System.EventArgs {
            
            private CC_PAC_075Row eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public CC_PAC_075RowChangeEvent(CC_PAC_075Row row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public CC_PAC_075Row Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591